ALTER TABLE user_credit_cards ALTER COLUMN credit_card_number TYPE TEXT;
ALTER TABLE users ADD UNIQUE(username);
TRUNCATE films RESTART IDENTITY CASCADE;
TRUNCATE actors RESTART IDENTITY CASCADE;
TRUNCATE film_actors RESTART IDENTITY CASCADE;
TRUNCATE film_genres RESTART IDENTITY CASCADE;